version: "3.7"
services:
  converter:
    build:
      context: Dockerfile.d/converter
    working_dir: /workspace
    volumes:
      - .:/workspace
    user: "${UID:-0}:${GID:-0}"
    command:
      - bash
      - -c
      - |
        mt-to-hugo-article-converter --config-file=migrate-config.yaml
  website:
    image: mazgi/hugo-static-website:hugo-0.57-2019.08.3
    working_dir: /mazgi.github.io.content
    command: hugo server --bind 0.0.0.0 --buildDrafts --buildFuture
    volumes:
      - ./proofreading:/mazgi.github.io.content
    ports:
      - "31313:1313"
