version: "2019.10.0"
output:
  base_path: data/converted
  content_path_fmt: "content/posts/%Y.%m"
  static_path_fmt: "static/posts/%Y.%m"
input:
  path: data/exported.txt
  start_at: 2018/01/01 00:00:00
  stop_at: 2018/12/31 23:59:59
asset_download:
  enabled: true
  base_url: "https://cdn-ak.f.st-hatena.com"
  filter:
    - regex: "^/"
    - regex: 'https?://cdn-ak\.f\.st-hatena\.com'
attribute_map:
  categories:
    from:
      - TAGS
      - CATEGORY
    values:
      book:
      event:
        - Conference
        - Interview
  tags:
    from:
      - TAGS
      - CATEGORY
    values:
      adobe-cc:
        - Adobe CC
      apple-ios:
        - iOS
      amazon-sagemaker:
        - sagemaker
      amazon-cloudfront:
        - Amazon CloudFront
      amazon-s3:
        - Amazon S3
      ansible:
      aws:
      aws-kms:
        - "AWS KMS"
      btrfs:
      c-language:
        - C
      c++:
      circleci:
        - CircleCI 2.0
      fluentd:
      git:
      hugo:
      infrastructure-as-code:
        - "Infrastructure as Code"
      device:
        - Gadget
        - LeapMotion
      gentoo:
      github:
      hardware:
        - ICT Infrastructure
        - IDC
        - ML115
      java:
      javascript:
        - JavaSript
      jenkins:
      jupyter-notebook:
        - Jupyter
      lvm:
      linux:
      mac:
      mongodb:
      mysql:
      network:
      objective-c:
      operation:
      ruby:
      ruby-on-rails:
      security:
      scala:
      screen:
      solaris:
      terraform:
      translation:
      unity:
      xen:
      zsh:
