baseURL = "https://mazgi.github.io/"
languageCode = "en-us"
title = "mazgi.log"
theme = "techlog-simple"
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "friendly"
enableGitInfo = false
enableRobotsTXT = true

[params]
description = "mazgi's tech blog"

[params.sns]
github = "mazgi"
twitter = "mazgi"
instagram = "mazgi"

[taxonomies]
category = "categories"
tag = "tags"

[languages]
[languages.en]
weight = 1
languageName = "English"

[languages.ja]
weight = 10
languageName = "日本語"
